create database CINEMA_BOOKING_SYSTEM;
use CINEMA_BOOKING_SYSTEM;
CREATE TABLE CUSTOMER (
CUSTOMER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50),LAST_NAME VARCHAR(50),
 PHONE VARCHAR(15));
CREATE TABLE MOVIE (
MOVIE_ID INT PRIMARY KEY,
TITLE VARCHAR(100),
GENRE VARCHAR(50),
DURATION INT);
CREATE TABLE TICKET (
TICKET_ID INT PRIMARY KEY,
SEAT_NUMBER INT,
SHOW_DATE DATE,
CUSTOMER_ID INT,
MOVIE_ID INT,
FOREIGN KEY (CUSTOMER_ID)REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (MOVIE_ID)REFERENCES MOVIE(MOVIE_ID));
CREATE TABLE BOOKING (BOOKING_ID INT PRIMARY KEY,
BOOK_DATE DATE,
CUSTOMER_ID INT,
TICKET_ID INT,
FOREIGN KEY (CUSTOMER_ID)REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (TICKET_ID)REFERENCES TICKET(TICKET_ID));
CREATE TABLE STAFF (STAFF_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
POSITION VARCHAR(50),
SALARY DECIMAL(10, 2));
CREATE TABLE CINEMA (CINEMA_ID INT PRIMARY KEY,
NAME VARCHAR(100),
LOCATION VARCHAR(100),
TOTAL_SEATS INT);
INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, PHONE) VALUES
(1, 'John', 'Doe', '1234567890'),
(2, 'Jane', 'Smith','0987654321');
INSERT INTO MOVIE (MOVIE_ID, TITLE, GENRE, DURATION) VALUES
(1,'Inception', 'Sci-Fi', 148),
(2,'The Godfather','Crime',175);
SELECT * FROM MOVIE;
INSERT INTO CINEMA (CINEMA_ID, NAME, LOCATION, TOTAL_SEATS) VALUES
(1, 'Cinema City','Downtown',200),
(2, 'Grand Cinema','Uptown',150);
SELECT * FROM CINEMA;
SELECT * FROM MOVIE WHERE GENRE = 'Sci-Fi';
SELECT * FROM MOVIE WHERE GENRE = 'Crime';
SELECT * FROM CUSTOMER;
SELECT * FROM movie
WHERE duration > 150;
SELECT * FROM movie
WHERE duration < 150;
SELECT * FROM CINEMA WHERE LOCATION = 'Downtown';
SELECT * FROM CINEMA WHERE LOCATION = 'Uptown';
SELECT * FROM CUSTOMER WHERE LAST_NAME = 'Ahmry';
SELECT * FROM CUSTOMER WHERE LAST_NAME = 'Smith';
SELECT * FROM CINEMA
WHERE TOTAL_SEATS < 160;
SELECT * FROM CINEMA
WHERE TOTAL_SEATS > 160;